CREATE DATABASE IF NOT EXISTS `projectdb`
USE `projectdb`;

CREATE TABLE IF NOT EXISTS `adm` (
  `USER_ID_ADM` int(11) NOT NULL,
  `NOME` varchar(200) NOT NULL,
  `LOGIN` varchar(100) NOT NULL,
  `SENHA` varchar(20) NOT NULL,
  `GRAU_ESCOLAR` varchar(100) DEFAULT NULL,
  `EQUIPE` varchar(100) DEFAULT NULL,
  `CARGO_ID` int(11) DEFAULT NULL,
  `TAG_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`USER_ID_ADM`),
  KEY `fk_cargoAdm` (`CARGO_ID`),
  KEY `fk_tagAdm` (`TAG_ID`),
  CONSTRAINT `fk_cargoAdm` FOREIGN KEY (`CARGO_ID`) REFERENCES `cargo` (`CARGO_ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_tagAdm` FOREIGN KEY (`TAG_ID`) REFERENCES `tags` (`TAG_ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;

CREATE TABLE IF NOT EXISTS `atividade` (
  `ATIVIDADE_ID` int(8) NOT NULL AUTO_INCREMENT,
  `ULTIMA_MOVIMENTACAO` date NOT NULL,
  `TAG_ID` int(11) NOT NULL,
  `USER_ID_VENDEDOR` int(11) NOT NULL,
  `USER_ID_ADM` int(11) NOT NULL,
  PRIMARY KEY (`ATIVIDADE_ID`),
  KEY `fk_TagAtividade` (`TAG_ID`),
  KEY `fk_UserAdmAtividade` (`USER_ID_ADM`),
  KEY `fk_UserVendedorAtividade` (`USER_ID_VENDEDOR`),
  CONSTRAINT `fk_TagAtividade` FOREIGN KEY (`TAG_ID`) REFERENCES `tags` (`TAG_ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_UserAdmAtividade` FOREIGN KEY (`USER_ID_ADM`) REFERENCES `adm` (`USER_ID_ADM`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_UserVendedorAtividade` FOREIGN KEY (`USER_ID_VENDEDOR`) REFERENCES `vendedor` (`USER_ID_VENDEDOR`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;

CREATE TABLE IF NOT EXISTS `cargo` (
  `CARGO_ID` int(11) NOT NULL AUTO_INCREMENT,
  `TITULO` varchar(100) NOT NULL,
  `SALARIO` float NOT NULL,
  PRIMARY KEY (`CARGO_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=57 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;

CREATE TABLE IF NOT EXISTS `incluir` (
  `ATIVIDADE_ID` int(8) NOT NULL,
  `PRODUTO_ID` int(11) NOT NULL,
  PRIMARY KEY (`ATIVIDADE_ID`,`PRODUTO_ID`),
  KEY `fk_ProdAtividade` (`PRODUTO_ID`),
  CONSTRAINT `fk_AtividadeProd` FOREIGN KEY (`ATIVIDADE_ID`) REFERENCES `atividade` (`ATIVIDADE_ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_ProdAtividade` FOREIGN KEY (`PRODUTO_ID`) REFERENCES `produtos` (`PRODUTO_ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;

CREATE TABLE IF NOT EXISTS `pessoa_fisica` (
  `CPF` int(11) unsigned zerofill NOT NULL,
  `NOME` varchar(300) NOT NULL,
  `RG` int(9) NOT NULL,
  `CARGO_ID` int(11) NOT NULL,
  PRIMARY KEY (`CPF`),
  KEY `fk_CargoIdPF` (`CARGO_ID`),
  CONSTRAINT `fk_CargoIdPF` FOREIGN KEY (`CARGO_ID`) REFERENCES `cargo` (`CARGO_ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;

CREATE TABLE IF NOT EXISTS `pessoa_juridica` (
  `CNPJ` bigint(14) unsigned zerofill NOT NULL DEFAULT 00000000000000,
  `CPF` int(11) unsigned zerofill NOT NULL,
  `RAZAO_SOCIAL` varchar(400) NOT NULL,
  `SITUACAO_RECEITA` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`CNPJ`),
  KEY `fk_CPF_PJ` (`CPF`),
  CONSTRAINT `fk_CPF_PJ` FOREIGN KEY (`CPF`) REFERENCES `pessoa_fisica` (`CPF`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;

CREATE TABLE IF NOT EXISTS `possuir` (
  `CNPJ` bigint(14) unsigned zerofill NOT NULL DEFAULT 00000000000000,
  `PRODUTO_ID` int(11) NOT NULL,
  PRIMARY KEY (`CNPJ`,`PRODUTO_ID`),
  KEY `fk_ProdCNPJ` (`PRODUTO_ID`),
  CONSTRAINT `fk_CNPJProd` FOREIGN KEY (`CNPJ`) REFERENCES `pessoa_juridica` (`CNPJ`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_ProdCNPJ` FOREIGN KEY (`PRODUTO_ID`) REFERENCES `produtos` (`PRODUTO_ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;

CREATE TABLE IF NOT EXISTS `produtos` (
  `PRODUTO_ID` int(11) NOT NULL AUTO_INCREMENT,
  `NOME_PRODUTO` varchar(200) NOT NULL,
  `TIPO_PRODUTO` varchar(100) NOT NULL,
  `REMUNERACAO_ID` int(11) NOT NULL,
  PRIMARY KEY (`PRODUTO_ID`),
  KEY `fk_RemuneracaoIdProduto` (`REMUNERACAO_ID`),
  CONSTRAINT `fk_RemuneracaoIdProduto` FOREIGN KEY (`REMUNERACAO_ID`) REFERENCES `remuneracao` (`REMUNERACAO_ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=45 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;

CREATE TABLE IF NOT EXISTS `remuneracao` (
  `REMUNERACAO_ID` int(11) NOT NULL AUTO_INCREMENT,
  `VALOR_PAGAMENTO` float NOT NULL,
  PRIMARY KEY (`REMUNERACAO_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=57 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;

CREATE TABLE IF NOT EXISTS `tags` (
  `TAG_ID` int(11) NOT NULL AUTO_INCREMENT,
  `TIPO` varchar(30) NOT NULL,
  `NOME` varchar(50) NOT NULL,
  PRIMARY KEY (`TAG_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=57 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;

CREATE TABLE IF NOT EXISTS `vendedor` (
  `USER_ID_VENDEDOR` int(11) NOT NULL,
  `NOME` varchar(200) NOT NULL,
  `LOGIN` varchar(100) NOT NULL,
  `SENHA` varchar(20) NOT NULL,
  `COMISSIONAMENTO` varchar(100) DEFAULT NULL,
  `CARGO_ID` int(11) DEFAULT NULL,
  `TAG_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`USER_ID_VENDEDOR`),
  KEY `fk_cargoVendedor` (`CARGO_ID`),
  KEY `fk_tagVendedor` (`TAG_ID`),
  CONSTRAINT `fk_cargoVendedor` FOREIGN KEY (`CARGO_ID`) REFERENCES `cargo` (`CARGO_ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_tagVendedor` FOREIGN KEY (`TAG_ID`) REFERENCES `tags` (`TAG_ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
